name: projects
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  shared_preferences: ^0.5.7+3
  pin_code_text_field: ^1.6.0
  firebase_messaging: ^6.0.16


dev_dependencies:
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/imgs/logo.jpeg"


flutter:


  uses-material-design: true

  assets:
    - assets/imgs/


  fonts:
    - family: CairoBold
      fonts:
        - asset: assets/fonts/cairo_bold.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: CairoSemiBold
      fonts:
        - asset: assets/fonts/Cairo-SemiBold.ttf

